### ISSUE TITLE
Handle the intricacies of determining the user's ip address

### ISSUE THREAD

**Issue by heliodor** [pinax/pinax-referrals#21]
Determining the user's ip address is a bit more complicated than just looking at the HTTP_X_FORWARDED_FOR header. https://github.com/un33k/django-ipware does a good job and is easy to use. Please consider incorporating it.

**Comment by paltman** [comment]
Thanks for the pointer @heliodor. This will be considered for the next release.

**Comment by KatherineMichel** [comment]
Closing this issue due to duplicate issue #45.
