### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by fcpauldiaz** [pinax/pinax-referrals#34]
Can you release the latest version so that it is compatible with django >= 1.10

**Comment by paltman** [comment]
You got it. I’m out of town this weekend with minimal access to my laptop. We will get released at some point next week.

**Comment by olivierbufalini** [comment]
Has the version compatible with Django >= 1.10 been released yet ?

**Comment by fcpauldiaz** [comment]
Please release it :(

**Comment by grahamu** [comment]
@fcpauldiaz @olivierbufalini @paltman We just released v2.3.0, available at PyPi: https://pypi.python.org/pypi/pinax-referrals/2.3.0. This version is tested and compatible with Django v2.0.
