### ISSUE TITLE
For tracking clicks to external links

### ISSUE THREAD

**Issue by Logmytech** [pinax/pinax-referrals#36]
Can pinax-referrlas be used for generating links for tracking clicks to external links like out.reddit.com or like how google generates links for tracking clicks?

**Comment by KatherineMichel** [comment]
Not that I'm aware of, but perhaps you can reconfigure it. I believe at the moment, it is set up to use the actual domain of the Django site you are developing through `Site.objects.get_current().domain`, unless I'm mistaken: https://github.com/pinax/pinax-referrals/blob/master/pinax/referrals/models.py#L59. Looks to me like the domain url is rendered in a view as JSON. https://github.com/pinax/pinax-referrals/blob/master/pinax/referrals/views.py#L36
