### ISSUE TITLE
Django 2.0 user.is_authenticated()

### ISSUE THREAD

**Issue by erikcw** [pinax/pinax-referrals#39]
Need to switch from `request.user.is_authenticated()` method call to `request.user.is_authenticated` property.

https://github.com/pinax/pinax-referrals/blob/master/pinax/referrals/models.py#L103

**Comment by grahamu** [comment]
Thanks for the bug report and PR @erikcw! New version 3.0.1 published on PyPi: https://pypi.python.org/pypi/pinax-referrals/.
