### ISSUE TITLE
Custom generate_code - request context

### ISSUE THREAD

**Issue by yn-coder** [pinax/pinax-referrals#41]
I want to overwrite `generate_code` in my project. But `generate_code` got only `referral_class` arg, and now request context.

So I can generate only some kind of random value or next id depend on `referrals` table data.

Can I generate code depend on user request context? For example, user id ?

**Comment by ranihorev** [comment]
You can fork the current version and add another argument to the save function, for example:

```
    def save(self, *args, **kwargs):
        if not self.code:
            self.code = settings.PINAX_REFERRALS_CODE_GENERATOR_CALLBACK(Referral, self.user)
        return super(Referral, self).save(*args, **kwargs) 
```
