### ISSUE TITLE
IP address pulling could use some modernization

### ISSUE THREAD

**Issue by mburke05** [pinax/pinax-referrals#45]
Using a single header field like `HTTP_X_FORWARDED_FOR` feels like it can be improved either by using it directly or mimicing their `META_PRECEDENCE_ORDER` field to take an array rather than a single field. Is there any reason I shouldn't work on this sort of change?

It looks like https://github.com/pinax/pinax-referrals/issues/21 references this a few years ago.

**Comment by KatherineMichel** [comment]
@paltman Any thoughts on whether @mburke05 should go ahead with this?

**Comment by ckrybus** [comment]
Getting client's IP address is quite complex (that's why https://github.com/un33k/django-ipware exists) and there will never be a solution which works for everyone. 

Why not make it a "callable setting"? For example:

pinax/referrals/utils.py
```
def get_client_ip(request):
    ip_address = request.META.get(
        settings.PINAX_REFERRALS_IP_ADDRESS_META_FIELD,
        ""
    )
    return ip_address
```

settings.py
```
PINAX_REFERRALS_GET_CLIENT_IP = "pinax.referrals.utils.get_client_ip"
```

**Comment by KatherineMichel** [comment]
Temporary fix provided by #52. Longterm fix still needed.

**Comment by ckrybus** [comment]
> I have added fix for this in #45. Please take a look.

@PetrDlouhy thanks for implementing this!

I'm not a maintainer of this project, but I've noticed a few things:

1. You are taking the first x_forwarded_for IP address, but actually it should be the last one (`ip = x_forwarded_for.split(",")[-1]`)
More info about this https://github.com/un33k/django-ipware/blob/master/README.md?plain=1#L186

2. It seems that there is already an established way of "defining callbacks":

callback.py
```python
def get_client_ip(request):
    (...)
```

conf.py
```python
class PinaxReferralsAppConf(AppConf):
    (...)
    GET_CLIENT_IP_CALLBACK = "pinax.referrals.callbacks.get_client_ip"

    def configure_get_client_ip_callback(self, value):
        return load_path_attr(value)
```

models.py
```python
(...)
ip_address = settings.PINAX_REFERRALS_GET_CLIENT_IP_CALLBACK(request)
```

3. This PR is a mix of refactoring and changing business logic - adding the x_forwarded_for  header is probably not good for backwards compatibility, but you could just make it configurable here and use the header in your custom callable.

+1 for merging this (with above fixes), then I could finally delete my IP address monkey patch :)

**Comment by PetrDlouhy** [comment]
@ckrybus Thank you very much for your review. 

1. In my case it is the first parameter. The `django-plans` application [takes the first parameter](https://github.com/django-getpaid/django-plans/blob/master/plans/utils.py#L5). And in the link you have posted is written `**If** your proxy server is configured such that the right-most IP address is that of the originating client, you
can indicate `right-most` as your proxy_order`, which sounds to me, that IP being on the right is the exception, not the common case.

But I can rewrite it to use the last parameter if you convince me that is the most common case. Or use the original behavior.
Or maybe we could start using `django-ipware` (if it is available), but that would be best to make in separate PR.

2. Very good point, I will rewrite it that way.

3. When I am looking at it now, I see it is not written as I intended. It should not change the logic that way.

Anyway, I have strong suspicion, that this project is dead. I have added important several PRs over last year (namely: update and testing in #68, security fix in #72) and none of it got merged. @paltman @KatherineMichel @jtauber @jbarham @grahamu
I have even tried to contact Pinax team on Slack, but without any answer.

**Comment by PetrDlouhy** [comment]
OK, I have refactored the PR. I used suggestions from paragraph 2.
I also rewritten the callback, that takes first IP if there is comma in the string. I can change it back to the original behavior, if you think, it would be harmful in some cases.

**Comment by paltman** [comment]
@ckrybus @PetrDlouhy would either/both of you like to be made maintainers on this project to carry it forward?  If so I can gladly hand you the "commit-bit" as well as ability to publish releases to PyPI.

**Comment by PetrDlouhy** [comment]
@paltman Yes, I would like to do it. Thanks. My PyPI username is `petr.dlouhy`.

**Comment by paltman** [comment]
@PetrDlouhy you've been granted access to both this repo and PyPI.  Let me know if you find anything not working or are otherwise blocked from merging and making releases.

Thanks for your help!  

@ckrybus Let me know if you would like to be added as well.

**Comment by PetrDlouhy** [comment]
@paltman Thank you very much. I will merge the two PRs mentioned in my original comment and try to fix testing infrastructure. Then @ckrybus can help me by reviewing my other PRs, if he wants to.

**Comment by ckrybus** [comment]
@paltman thanks for the offer, I think I'll stick to being a regular contributor for now, @PetrDlouhy seems to have a clear plan :rocket: 

@PetrDlouhy you can always add me as a reviewer to a pr, then I'll try to do the review in a timely manner. Otherwise I'm just lurking and I'll only comment if I see a bug, or something is unclear, etc.

**Comment by ckrybus** [comment]
> 1. In my case it is the first parameter. The `django-plans` application [takes the first parameter](https://github.com/django-getpaid/django-plans/blob/master/plans/utils.py#L5). And in the link you have posted is written `**If** your proxy server is configured such that the right-most IP address is that of the originating client, you can indicate `right-most` as your proxy_order`, which sounds to me, that IP being on the right is the exception, not the common case.
> 
> But I can rewrite it to use the last parameter if you convince me that is the most common case. Or use the original behavior. Or maybe we could start using `django-ipware` (if it is available), but that would be best to make in separate PR.

@PetrDlouhy Then I'm for removing `.split(",")[0]` from the PR, because the right solution is not clear. This way the change is also fully backwards-compatible.

Regarding `django-ipware` this could be an example in the docs in some future pr: "how to integrate `django-ipware` with `pinax-referrals`".  Personally I'm using a similar callback as you. Just the callback solution is already a huge win, anyone can now modify it easily without monkey patching :-)

**Comment by PetrDlouhy** [comment]
@ckrybus OK, I have restored the original behavior of that function, so now the #73 is only about the callback.

I have fixed the testing, coverage reporting, migration checking for the whole project. I have rebased my PRs and added tests.

So PRs #69, #73, #72 should be ready for merge. I will leave them until Monday, and then merge them and make new release. You could review them until then @paltman @ckrybus.

**Comment by ckrybus** [comment]
@PetrDlouhy in my opinion all three PRs look good, for #72 I've added a small comment.

Thanks for this!
