### ISSUE TITLE
IP address save to database

### ISSUE THREAD

**Issue by jffin** [pinax/pinax-referrals#46]
Hello I'm experiencing issue during saving to database.

ERROR:  value too long for type character varying(45)
STATEMENT:  INSERT INTO "referrals_referralresponse" ("referral_id", "session_key", "user_id", "ip_address", "action", "target_content_type_id", "target_object_id", "created_at") VALUES (1242, 'sfkjgjsdfkdsfjdsfsdg', NULL, '4c13:1234:aa:44:1:1:afec:a11b, 238.522.314.142', 'RESPONDED', NULL, NULL, '2018-3-19T15:33:17.353223+00:00'::timestamptz) RETURNING "referrals_referralresponse"."id"

are there any way to fix this issue temporarily?

**Comment by KatherineMichel** [comment]
@jffin This has been temporarily fixed by #52.
