### ISSUE TITLE
'Settings' object has no attribute 'PINAX_REFERRALS_CODE_GENERATOR_CALLBACK'

### ISSUE THREAD

**Issue by pjain0110** [pinax/pinax-referrals#50]
It is stated in the documentation that PINAX_REFERRALS_CODE_GENERATOR_CALLBACK defaults to pinax.referral.utils.generate_code. But could not fine this function in the utils.py file.

**Comment by ckrybus** [comment]
You'll find it in pinax/referrals/callbacks/generate_code.py

**Comment by KatherineMichel** [comment]
@pjain0110 I merged the correction from @ckrybus just now.
