### ISSUE TITLE
Django v3 compatibility

### ISSUE THREAD

**Issue by ipeterov** [pinax/pinax-referrals#55]
Now that Django v3 is out, [python_2_unicode_compatible is removed](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis).

Is it possible to remove it from the project?

**Comment by KatherineMichel** [comment]
@ipeterov Thank you for creating an issue and PR for this. We are working on dropping/adding support for old/new Python and Django versions. I will note this and hopefully merge soon.

**Comment by mugambiwarwema** [comment]
Any word on this bug/issue?

**Comment by carlosnasillo** [comment]
> Any word on this ?

Second this.

**Comment by KatherineMichel** [comment]
@ipeterov Thanks again for doing this. I've merged the PR and it should be published soon as well as noted in a release blog post. cc @mugambiwarwema @carlosnasillo

**Comment by carlosnasillo** [comment]
@KatherineMichel @ipeterov - Thank you both!
