### ISSUE TITLE
No pypi release versions after 3.0.3?

### ISSUE THREAD

**Issue by pavitrakumar78** [pinax/pinax-referrals#58]
Hi,

I don't see a release package for 3.0.5 on pypy. The lastest is 3.0.3, but I need at least 3.0.5 because it contains a fix for the IP address field size and I think it's important to have this fix in the most recent release. Can you please update the releases for pinax? or is there a reason why there hasn't been a release since 3.0.3?

Thanks!

**Comment by KatherineMichel** [comment]
@pavitrakumar78 I will publish soon. I was recently given access.

**Comment by pavitrakumar78** [comment]
Thanks! I'll close this question.

**Comment by KatherineMichel** [comment]
@pavitrakumar78 I've just tagged and published a new release. :) https://pypi.org/project/pinax-referrals/
