### ISSUE TITLE
Add self to the code generation callback

### ISSUE THREAD

**Issue by jTiKey** [pinax/pinax-referrals#59]
Would it be possible to add self to:

self.code = settings.PINAX_REFERRALS_CODE_GENERATOR_CALLBACK(**self,** Referral)

so the referral url could use the username?

**Comment by KatherineMichel** [comment]
Any thoughts on this, @jtauber @paltman?

**Comment by jTiKey** [comment]
I could work around it with just manually saving the code after a Referral was created:

referred = Referral.create(
            user=self.user,
            redirect_to="account_signup",
        )
referred.code = self.user.username
referred.save()
