### ISSUE TITLE
Pending Migration on v4.0.1

### ISSUE THREAD

**Issue by ghost** [pinax/pinax-referrals#62]
**Describe the bug**
It appears like there are pending migrations in the release of 4.0.1. I noticed that my local machine had an additional migration than my remote server when my build pipeline alerted me I had "pending" migrations:

```bash
Your models have changes that are not yet reflected in a migration, and so won't be applied.     
```

**Reproduce behavior**
Clone repo, activate fresh virtual environment, `pip install -e .`, and run `python makemigrations.py`. On my machine, this yields:

```bash
(venv) crawfordleeds@Crawfords-MacBook-Pro pinax-referrals % python makemigrations.py 
Migrations for 'referrals':
  pinax/referrals/migrations/0004_auto_20201027_2047.py
    - Alter field target_content_type on referralresponse
    - Alter field target_object_id on referralresponse
```

**Expected behavior**
I would expect no output

It seems we just need to add these new migrations to the codebase; am I missing something? If that makes sense, I'm happy to make a PR accordingly.

**Comment by nguyenthanhquang152** [comment]
@PetrDlouhy @KatherineMichel Hi guys, in the commit d3411eed41fce6599f1de79f43cfb5f8f9266455, you modified field constraints but didn't make migrations for this change.

**Comment by jerinpetergeorge** [comment]
I hope this #65 will fix the issue @KatherineMichel
