### ISSUE TITLE
Make pinax cookie last longer than a single session

### ISSUE THREAD

**Issue by pavitrakumar78** [pinax/pinax-referrals#66]
Hi,

I'm using pinax referrals for one of my projects and I would like the referral link to store or persist the cookie for longer than a single session so that even if a user closes the window and visits the same page in say, 2 or 3 days the referral still gets recorded. 

Right now, the expires/max-age is set to 'Session' is there a way to change this to a 60-day duration or something similar?

Thank you!

**Comment by bruecksen** [comment]
@pavitrakumar78 version 4.0.2 now has a new setting `PINAX_COOKIE_MAX_AGE`

**Comment by pavitrakumar78** [comment]
@bruecksen Yep! :) https://github.com/pinax/pinax-referrals/pull/67
