### ISSUE TITLE
Incompatible with django-registration 1.0

### ISSUE THREAD

**Issue by erikcw** [pinax/pinax-referrals#8]
Anafero fails to attach ReferralResponses to users who were authenticated in the same view (as part of the same request).

When using `django-registration`s "simple" backend, the `User` object is created if the form is valid and then the user is immediately authenticated.

If you attempt to call `Referral.record_response(request, "ACCOUNT_REGISTERED")` inside the registration view's `register` method, the response is not recorded correctly because the `Referral.referral_for_request()` cannot find any `ReferralResponse` objects for the authenticated user.

This is because the user's session_key has changed as a result of being authenticated in the view, and the ReferralResponse objects have not yet been updated by the anafero middleware to point to the new user (ie `Referral.link_responses_to_user`).

Adding a call to `SessionJumpingMiddleware().process_request(request)` inside the view seems to correct the problem (Sample code below).  Since this is really just a hack, it would probably make sense to update https://github.com/eldarion/anafero/blob/master/anafero/models.py#L86 to check for the anafero cookie in addition to searching user and session_key.

Django 1.5.5
Anafero 1.0.1
django-registration 1.0

```python
from registration.backends.simple.views import RegistrationView as SimpleRegistrationView

from anafero.models import Referral
from anafero.middleware import SessionJumpingMiddleware


class UserRegistrationView(SimpleRegistrationView):
    """
    The main user registration backend.
    1) Collect user contact info.
    2) Collect payment info
    3) Redirect to thankyou page
    """

    def register(self, request, **cleaned_data):
        new_user = super(UserRegistrationView, self).register(request, **cleaned_data)
        new_user.first_name = cleaned_data['first_name']
        new_user.last_name = cleaned_data['last_name']
        new_user.save()
        profile = new_user.get_profile()
        profile.phone = cleaned_data['phone']
        profile.address = cleaned_data['address']
        profile.address2 = cleaned_data['address2']
        profile.city = cleaned_data['city']
        profile.state = cleaned_data['state']
        profile.zip_code = cleaned_data['zip_code']
        profile.country = cleaned_data['country']

        # normally anafero middleware would handle this, but
        # because django-registration calls `login()`, the session_key
        # changes and `Referral.record_response()` won't work since the middleware hasn't
        # performed this cleanup
        anafero_middleware = SessionJumpingMiddleware()
        anafero_middleware.process_request(request)

        profile.affiliate_referral = Referral.record_response(request, "ACCOUNT_REGISTRATION")
        profile.save()
        return new_user

    def get_form_class(self, request):
        """
        Return the default form class used for user registration.
        """
        return UserRegistrationForm

    def get_form(self, *args, **kwargs):
        form = super(UserRegistrationView, self).get_form(*args, **kwargs)

        # to enable re-use of this view for similar registration forms.
        if self.kwargs.get('form_action'):
            form.helper.form_action = reverse(self.kwargs.get('form_action'))
        return form

```

**Comment by embedded1** [comment]
Thanks for sharing this!
What about pushing a fix for this?

**Comment by paltman** [comment]
It's not clear to me why the middleware would not work unless cookies were not enabled.  The middleware was added to handle specifically the case of linking pre-auth user activity with post auth user activity.

**Comment by embedded1** [comment]
As I see it, the pre-auth and post-auth happens on the same request. 
This is the reason why you need to call the process_request just after authentication.

**Comment by ossanna16** [comment]
@embedded1 Has this issue been resolved, meaning can I close this issue? :)

**Comment by embedded1** [comment]
yes

**Comment by ossanna16** [comment]
Awesome!
